server:
  port: 8091
elpis:
  url: http://192.168.200.100:5001
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1500MB
      max-request-size: 1500MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/5703test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true

  main:
    allow-circular-references: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sydney.pojo
